### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by ToneZe** [ming71/TIOE#3]
1.来自TIOE-main/utils/datasets.py
按照TIOE-main/config/HRSC2016/HRSC2016.yaml 格式划分数据集
labels, shapes = zip(*[cache[x] for x in self.img_files])
输出的标签为None，能否提供下可训练的标签内部格式？
2.另外，关于train.py代码中没有yolov5代码中的eval过程，那么数据集的验证结果如何实现

**Comment by ToneZe** [comment]
After sh compile.sh
In file included from /root/TIOE/utils/ext/rotate_overlap_diff/cuda_op/sort_vert.cpp:1:0:
/root/TIOE/utils/ext/rotate_overlap_diff/cuda_op/utils.h:27:64: warning: backslash-newline at end of file
 #define CHECK_IS_BOOL(x)                                       \
                                                                 
creating build/lib.linux-x86_64-3.8
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 /root/TIOE/utils/ext/rotate_overlap_diff/cuda_op/build/temp.linux-x86_64-3.8/sort_vert.o /root/TIOE/utils/ext/rotate_overlap_diff/cuda_op/build/temp.linux-x86_64-3.8/sort_vert_kernel.o -L/usr/local/lib/python3.8/dist-packages/torch/lib -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.8/sort_vertices.cpython-38-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/sort_vertices.py to sort_vertices.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying sort_vertices.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sort_vertices.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sort_vertices.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sort_vertices.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
__pycache__.sort_vertices.cpython-38: module references __file__
creating dist
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
creating /usr/lib/python3.8/site-packages/sort_vertices-0.0.0-py3.8-linux-x86_64.egg
Extracting sort_vertices-0.0.0-py3.8-linux-x86_64.egg to /usr/lib/python3.8/site-packages
byte-compiling /usr/lib/python3.8/site-packages/sort_vertices-0.0.0-py3.8-linux-x86_64.egg/sort_vertices.py to sort_vertices.cpython-38.pyc
Adding sort-vertices 0.0.0 to easy-install.pth file

Installed /usr/lib/python3.8/site-packages/sort_vertices-0.0.0-py3.8-linux-x86_64.egg
Processing dependencies for sort-vertices==0.0.0
Finished processing dependencies for sort-vertices==0.0.0

1.But sh train.sh, the error:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "tools/train.py", line 26, in <module>
    from models.yolo import Model
  File "/root/TIOE/./models/yolo.py", line 14, in <module>
    from models.common import Conv, Bottleneck, SPP, DWConv, Focus, BottleneckCSP, Concat, NMS
  File "/root/TIOE/./models/common.py", line 6, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 26, in <module>
    from utils.general import non_max_suppression
  File "/root/TIOE/./utils/general.py", line 28, in <module>
    from models.yolo import Model
  File "/root/TIOE/./models/yolo.py", line 14, in <module>
    from utils.ext.rotate_overlap_diff.oriented_iou_loss import cal_iou 
  File "/root/TIOE/./utils/ext/rotate_overlap_diff/oriented_iou_loss.py", line 3, in <module>
    from .box_intersection_2d import oriented_box_intersection_2d
    from models.common import Conv, Bottleneck, SPP, DWConv, Focus, BottleneckCSP, Concat, NMS  File "/root/TIOE/./utils/ext/rotate_overlap_diff/box_intersection_2d.py", line 8, in <module>

  File "/root/TIOE/./models/common.py", line 6, in <module>
    from .cuda_op.cuda_ext import sort_v
  File "/root/TIOE/./utils/ext/rotate_overlap_diff/cuda_op/cuda_ext.py", line 4, in <module>
    from utils.general import non_max_suppression
  File "/root/TIOE/./utils/general.py", line 28, in <module>
    import sort_vertices
ModuleNotFoundError: No module named 'sort_vertices'
    from utils.ext.rotate_overlap_diff.oriented_iou_loss import cal_iou 
  File "/root/TIOE/./utils/ext/rotate_overlap_diff/oriented_iou_loss.py", line 3, in <module>
    from .box_intersection_2d import oriented_box_intersection_2d
  File "/root/TIOE/./utils/ext/rotate_overlap_diff/box_intersection_2d.py", line 8, in <module>
    from .cuda_op.cuda_ext import sort_v
  File "/root/TIOE/./utils/ext/rotate_overlap_diff/cuda_op/cuda_ext.py", line 4, in <module>
    import sort_vertices
ModuleNotFoundError: No module named 'sort_vertices'

**Comment by ToneZe** [comment]
有个很奇怪的现象，sh prepaer.sh貌似在30系显卡上可 以正常运行，在其他的显卡上 就会出现ModuleNotFoundError: No module named 'sort_vertices'
